name: dart_date
description: Date manipulation library. DateTime extensions. Also includes an Interval object.
version: 1.3.2
homepage: https://github.com/xantiagoma/dart_date

environment:
  sdk: ">=3.0.2 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  intl: ^0.19.0
  timeago: ^3.6.1

dev_dependencies:
  test: ^1.25.5
